config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
 

root 'teams#index'
  get 'home/index'
  get 'home/about_us'
  
  resources :rounds

resources :teams do
  resources :games
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
end

app/models/round.rb
class Round < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
has_many :games
accepts_nested_attributes_for :games


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
   
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
   @team = Team.find(params[:team_id])
    @game = @team.games.create(game_params)
         @game = Game.new

    respond_to do |format|
      if @game.save
        format.html { redirect_to root_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { redirect_to root_path, notice: 'Game was successfully created. not good ' } #Note else one
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update

    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy

    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
            @team = Team.find(params[:team_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:team_id, :round_id, :team_catagory, :game_point, :game_time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:round_map, :round_room)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  
  Team.all.each do |id_number| 
  total_point = Game.where(team_id: (id_number))
  sum_total_point= total_point.sum(:game_point)
  
  add_game_point = Team.where(id: (id_number))
  add_game_point.update(team_point: sum_total_point)
  
  game_size = total_point.size
  add_game_size = Team.where(id: (id_number))
  add_game_size.update(games_play: game_size)

  best_time_from_games = total_point.minimum(:game_time)
  add_best_time = Team.where(id: (id_number))
  add_best_time.update(best_time: best_time_from_games)



end
@teams = Team.order(team_group: :desc, team_point: :desc, best_time: :asc)
@line_race_teams = Team.where(team_category: "Line Race").order(team_group: :desc, team_point: :desc, best_time: :asc)
@open_sumo_teams = Team.where(team_category: "Sumo").order(team_group: :desc, team_point: :desc, best_time: :asc)


  end

  # GET /teams/1
  # GET /teams/1.json
  def show

  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit

  end

  # POST /teams
  # POST /teams.json
  def create

    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update

    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy

    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:team_name, :team_school, :team_category, :team_point, :team_group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
  case flash_type
  when "success"
    "alert-success"   # Green
  when "error"
    "alert-danger"    # Red
  when "alert"
    "alert-warning"   # Yellow
  when "notice"
    "alert-info"      # Blue
  else
    flash_type.to_s
  end
end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Round</th>
      <th>Team catagory</th>
      <th>Game point</th>
      <th>Game time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.team_id %></td>
        <td><%= game.round_id %></td>
        <td><%= game.team_catagory %></td>
        <td><%= game.game_point %></td>
        <td><%= game.game_time %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_team_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', team_games_path %>

app/views/games/show.html.erb
<p>
  <strong>Team:</strong>
  <%= @game.team_id %>
</p>

<p>
  <strong>Round:</strong>
  <%= @game.round_id %>
</p>

<p>
  <strong>Team catagory:</strong>
  <%= @game.team_catagory %>
</p>

<p>
  <strong>Game point:</strong>
  <%= @game.game_point %>
</p>

<p>
  <strong>Game time:</strong>
  <%= @game.game_time %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/about_us.html.erb
<h1>about this app</h1>
<h3>this app for ARC 3 Robotic - SCS APP </h3>
<h3>Done by Tarek Sheikh AL-Shbab</h3>

app/views/home/index.html.erb
<h1>Hello, Wrold!</h1>
<p>ARC Roboitcs</p>
<h3>Comming soon</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ARC 3 - SCS - App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "ARC 3 - APP", root_path, class:"navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "Home", root_path%></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
       <% if current_user %>
       <p class="navbar-text"><%= current_user.email %></p>

        <%= menu_item "Log Out", destroy_user_session_path, :method => :delete %>
    <% else %>
             <%= menu_item "Log in", new_user_session_path %>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= render partial: "shared/flash_messages", flash: flash %> 

<div class="container-fluid">
    <%= yield %>
    </div>
    <div class="navbar container-fluid navbar-default navbar-fixed-bottom"><p class="navbar-text">ARC 3 App - Tarek </p></div>

  </body>
</html>

app/views/rounds/_form.html.erb
<%= form_for(round) do |f| %>
  <% if round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_map %>
    <%= f.number_field :round_map %>
  </div>

  <div class="field">
    <%= f.label :round_room %>
    <%= f.number_field :round_room %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Round map</th>
      <th>Round room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.round_map %></td>
        <td><%= round.round_room %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p>
  <strong>Round map:</strong>
  <%= @round.round_map %>
</p>

<p>
  <strong>Round room:</strong>
  <%= @round.round_room %>
</p>

<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>